In [2]:
import pandas as pd

df1 = pd.read_csv("results/logisitc_by_msa.csv", index_col = 0)
df1 = df1.drop(columns = ["index"])

df2 = pd.read_csv("results/logistic_by_zipcode.csv", index_col = 0)

FileNotFoundError: [Errno 2] No such file or directory: 'results/logisitc_by_msa.csv'

In [ ]:
df1.head()

,zip_code,income_2030,rent_2030,college_2030,msa_name,gentrification_prob_2035
0,602,19337,3931,22.6,"Aguadilla-Isabela-San Sebastian, PR MSA",0.508726
1,603,19302,8080,23.7,"Aguadilla-Isabela-San Sebastian, PR MSA",0.497679
2,610,21663,2816,16.6,"Aguadilla-Isabela-San Sebastian, PR MSA",0.524413
3,631,14914,373,16.6,"Aguadilla-Isabela-San Sebastian, PR MSA",0.506732
4,662,18862,7203,19.4,"Aguadilla-Isabela-San Sebastian, PR MSA",0.501753

In [ ]:
df2.head()

,zip_code,income_2012,income_2013,income_2014,income_2015,income_2016,income_2017,income_2018,income_2019,income_2020,...,median_contract_rent_2018,median_contract_rent_2019,median_contract_rent_2020,median_contract_rent_2021,median_contract_rent_2022,median_contract_rent_2023,income_2030,rent_2030,college_2030,gentrification_prob_2035
0,602,15106.0,15663.0,16353.0,16079.0,15511.0,16190.0,16358.0,16807.0,16771.0,...,3257.0,3212.0,3034.0,3076.0,3147.0,3103.0,19337,3931,22.6,0.506076
1,603,15079.0,15485.0,16323.0,16804.0,16681.0,16645.0,16603.0,16049.0,15786.0,...,8081.0,8110.0,8333.0,8041.0,8366.0,8389.0,19302,8080,23.7,0.538475
2,610,16923.0,16707.0,17265.0,17475.0,17751.0,18741.0,19309.0,19898.0,20167.0,...,2064.0,2037.0,2288.0,2482.0,2389.0,2423.0,21663,2816,16.6,0.472766
3,612,18111.0,17848.0,17752.0,17229.0,17208.0,17744.0,18171.0,18741.0,19402.0,...,7894.0,8485.0,8865.0,8853.0,8781.0,9103.0,23184,9031,26.5,0.554547
4,616,16279.0,15342.0,15115.0,13705.0,14490.0,14918.0,16018.0,17007.0,18903.0,...,858.0,831.0,798.0,976.0,1027.0,1047.0,20838,1014,17.5,0.464763